### ISSUE TITLE
Multiple instances of pseudo-daemon running in parallel.

### ISSUE THREAD

**Issue by diggersworld** [hammerstonedev/laravel-pseudo-daemon#5]
Hi, I've been using this package for a few years now, and overall it's great.

However, from time to time I've experienced scenarios where I end up with multiple instances of the same pseudo-daemon running in parallel, which is unwanted. The root of the problem stems from Laravel's `withoutOverlapping` functionality. By default, the method sets a cache period of 24 hours. Regardless of the time set, once the cache file expires, an additional processor is started in parallel.

In order to prevent this issue, I've ended up making the daemon process perform a chunk of work and then stop. I then base the `withoutOverlapping` time, with some leeway, around an estimated time period for that chunk of work, e.g. say the work takes 45 minutes, I'll set `withoutOverlapping` to 60 minutes. In rare circumstances where the processor has then taken longer than the allocated 60 minutes, a second pseudo-daemon has then kicked off, in parallel. 

My reason for opening this issue is two-fold, [1] I'm either missing something when using this package; or [2] the reliance on `withoutOverlapping` has an unforeseen issue.

**Comment by aarondfrancis** [comment]
Interesting, thanks for opening this issue! 

I think I've never run into this because I've never had a task take longer than 24 hours. Is there a reason you're dropping the `withoutOverlapping` timeout to 60 minutes, down from 24 hours? In theory the pseudo-daemon should die [after 60 minutes](https://github.com/hammerstonedev/laravel-pseudo-daemon/blob/main/src/IsPseudoDaemon.php#L113). Of course an iteration of the control loop has to run, so it could take much longer if your processing code takes longer. 

For example, if your pseudo-daemon starts at 00:00, the processing code you write takes 6 hours, then the pseudo-daemon _should_ die at 06:00 and be restarted at 06:01 by the Kernel. As long as you're within 24 hours you should be fine. 

Am I missing something in your setup? I might be! Do let me know.

**Comment by diggersworld** [comment]
Ha, interestingly I had missed/forgotten about the `restartAfterMinutes` timeout. Maybe that's the missing piece. However, I think my reason for reducing the `withoutOverlapping` timeout still raises potential issues. I'll expand on my current implementation(s).

I'm mostly using the pseudo-daemons to power stream processors. Some streams contain many events. Some of those events can take a while to process depending on the desired outcome. We're talking seconds per event but when there are a lot of events those seconds become minutes, hours, etc. So I tend to chunk the events per cycle, in order to allow the pseudo-daemon to check its own logic and determine whether to run another cycle, sleep, stop, etc.

The reason for lowering the `withoutOverlapping` timeout is that in the past my team has experienced issues where PHP has quite simply died on the server. The command that then removes the mutex file created by `withoutOverlapping` is then never executed, so the mutex file remains in situ. When PHP eventually restarts the Kernel doesn't trigger the new process until that mutex file expires. So rather than waiting up to 24 hours for the mutex file to expire, I shorten the timeout window, and thus the lifetime of the mutex file, to an hour.

When putting all these time-based parameters together I end up doing a calculation like so:
```text
IF each event takes approximately 2 seconds to process
THEN 150 events will take approximately 300 seconds (5 minutes) to process.

IF pseudo daemon is configured to run 10 cycles with no sleep
THEN that'll take approximately 50 minutes.
```
This then leaves a 10 minute grace period should any events be slower than expected.

Should any of those cycles still be running at 60 minutes, that's when the new pseudo-daemon appears in parallel for the same process. I have thought about writing a file to the server to prevent this but I think I would just end up with the same issue as the lingering mutex file (potentially).

Regardless, it sounds like I simply need to allocate a decent amount of time between the `withoutOverlapping` timeout and the `restartAfterMinutes` timeout, and ensure the cycles are short enough that they can trigger the right functionality within that time allocation.

Thank you, I think that's brought clarity, simply by talking it through.

**Comment by aarondfrancis** [comment]
> The reason for lowering the withoutOverlapping timeout is that in the past my team has experienced issues where PHP has quite simply died on the server. 

Yeah, I've totally been there. That's such a hard problem to debug when the mutex is hanging around but the process is dead.

I think shortening to 60 minutes is totally fine! I would also say that restarting a daemon is relatively cheap, taking _at most_ 60 seconds (because the Kernel runs at the top of the minute.) So if you want to set your `restartAfterMInutes` to 20 or 30, you'll have _plenty_ of headroom, and be "offline" for a maximum of 2 minutes per hour. 

If you wanted to get tricky, you could try to kill your daemon when `now()->seconds > 50` to minimize downtime. Not sure if that's worth the effort tho 😂

**Comment by diggersworld** [comment]
Great, I'll look at restarting the daemon more often. Thank you for your support on this matter.
